### ISSUE TITLE
Can't use formData to upload a folder

### ISSUE THREAD

**Issue by broncowdd** [silverwind/uppie#6] opened 2017-01-18 10:25 UTC
Hi,
when I try your script like this:
```
uppie(document.documentElement, function(event, formData, files) {
        var xhr = new XMLHttpRequest();
        console.log(formData);
        xhr.open('POST', 'get.php');
        xhr.send(formData);

      });
```

The formData seems empty and my get.php script doesn't receive any POST/FILE data...

I'm sure I'm doing something wrong, but I don't get it :-)

Could you enlighten me, please ?

(firefox 50/chromium 55) linux mint

Thanks !

**Comment by silverwind** [comment] 2017-01-18 13:54
Can you try on https://silverwind.io/uppie/example.html with those browsers? Oh, and do you perhaps see any errors in the browser console?

**Comment by broncowdd** [comment] 2017-01-18 14:08
There's no problem with your demo page: the list is correct and I see no errors...
I want to use uppie to upload a folder to my server (php)... 
To do it, I try to see the formData content with a console.log in this script:
```
      function post(url,data,async){
        if (!async){async=true;}
        request = new XMLHttpRequest();
        request.open('POST', url, async);        
        request.send(data);
        request.onreadystatechange=function(){
          if (request.readyState==4 && request.status==200){
            return request.responseText;
          }     
        }
      }
      /* used on an input element */
      var uppie = new Uppie();
      uppie(document.querySelectorAll(".input"), function(event, formData, files) {        
        console.log(formData);
        post('get.php',formData);
      });
      /* used on a dropzone element */
      var uppie = new Uppie();
      uppie(document.documentElement, function(event, formData, files) {
        var xhr = new XMLHttpRequest();
        console.log(formData);
        xhr.open('POST', 'get.php');
        xhr.send(formData);

      });

```
In the console, I only see this:

![capture du 2017-01-18 14-59-27](https://cloud.githubusercontent.com/assets/4249696/22066878/42dd1de0-dd8f-11e6-9564-ace20ac32332.png)

My problem is to «convert» the folder content list into a set of file objects to send them to php with XMLHttpRequest.

My php script does'nt receive any $_FILE or $_POST data...
```
<?php
var_dump($_FILES);
var_dump($_POST);
var_dump($_GET);
```
![capture du 2017-01-18 15-05-34](https://cloud.githubusercontent.com/assets/4249696/22067015/b1684334-dd8f-11e6-8d40-29ad92d3111f.png)


Maybe I'm too noob in JS programming to use it ;-)

**Comment by silverwind** [comment] 2017-01-18 14:24
Ah, it's probably PHP unable to detect the [formdata format](https://github.com/silverwind/uppie#formdata-format). I'll have to try with your PHP script to see what's the issue. What version of PHP are you running?

**Comment by broncowdd** [comment] 2017-01-18 15:33
I'm running php 7 on linux mint...
The formdata is sent with those headers, isn't it ? : 
![capture du 2017-01-18 16-32-46](https://cloud.githubusercontent.com/assets/4249696/22070293/c5259d20-dd9b-11e6-9682-11b3750b7115.png)

So I need php to handle those specific headers and not to wait for $_FILES data ?

**Comment by silverwind** [comment] 2017-01-18 16:55
Those are not headers. What you're seeing is the `multipart/form-data` encoded request body. I assume the PHP-builtin `$_FILES` handling isn't sophisticated enough to support directory uploads and a custom parser maybe necessary.

A quick search turned up https://packagist.org/packages/riverline/multipart-parser, which looks promising, 
but I'm by no means a PHP expert :)

**Comment by silverwind** [comment] 2017-01-18 17:00
On the other hand, I found http://www.w3bees.com/2013/03/directory-upload-using-html-5-and-php.html which looks like it might work with what PHP got. Will test.

**Comment by broncowdd** [comment] 2017-01-18 17:22
Ok thanks a lot for all those informations ;-)

**Comment by broncowdd** [comment] 2017-01-18 17:26
This script is good but my problem is that my app needs to use drag & drop for folders and I can't convert the list of files into a php $_FILES format :-/

**Comment by silverwind** [comment] 2017-01-18 17:41
I've identified one issue where only one file is found in `$_FILES` because PHP expects the name field to contain `[]` for multiple files, so it should be `files[]` as opposed to `file` which I'm doing. That should be fixable, I'll have to investigate if this isn't breaking other scripts.

But I cannot really reproduce your issue of the empty `$_FILES`. I'm running PHP 7.0.14 with default options (http://php.net/manual/en/ini.core.php#ini.sect.file-uploads). Here's what I upload:
````
.
`-- dir
    |-- file.txt
    `-- subdir
        `-- file2.txt
````

#### Request:
````
-----------------------------11407556713142
Content-Disposition: form-data; name="files[]"; filename="dir/file.txt"
Content-Type: text/plain


-----------------------------11407556713142
Content-Disposition: form-data; name="files[]"; filename="dir/subdir/file2.txt"
Content-Type: text/plain


-----------------------------11407556713142--
````
#### Response (`<?php var_dump($_FILES); ?>`)
````
array(1) {
  ["files"]=>
  array(5) {
    ["name"]=>
    array(2) {
      [0]=>
      string(8) "file.txt"
      [1]=>
      string(9) "file2.txt"
    }
    ["type"]=>
    array(2) {
      [0]=>
      string(10) "text/plain"
      [1]=>
      string(10) "text/plain"
    }
    ["tmp_name"]=>
    array(2) {
      [0]=>
      string(14) "/tmp/phpR2nGN9"
      [1]=>
      string(14) "/tmp/phpycqRv3"
    }
    ["error"]=>
    array(2) {
      [0]=>
      int(0)
      [1]=>
      int(0)
    }
    ["size"]=>
    array(2) {
      [0]=>
      int(0)
      [1]=>
      int(0)
    }
  }
}
````

As you see, PHP just drops the path information of the request. So I think you definitely need a custom parser if you want to represent directories in PHP, unfortunately.

**Comment by broncowdd** [comment] 2017-01-18 17:51
\o/ woohooo ! Changing «file» into «file[ ]» in uppie seems to allow php to recognize the $_FILES data ;-) 
I'll try to handle the actual upload and I come back :-)

**Comment by silverwind** [comment] 2017-01-18 18:10
I went ahead and changed it (released as 1.0.0). I think it's unlikely that the `name` field is going to break much, and if it helps PHP identify a multi-file upload correctly, so be it.

**Comment by broncowdd** [comment] 2017-01-18 18:40
A strange thing:  the file array has a maximum of 20 items when I expect 81 (the number of files in the dropped folder)... 
![capture du 2017-01-18 19-39-14](https://cloud.githubusercontent.com/assets/4249696/22077769/d2ed1702-ddb5-11e6-957b-f2522bd1eb1a.png)

**Comment by silverwind** [comment] 2017-01-18 19:22
Adjust `max_file_uploads` in your php.ini ;)

http://php.net/manual/en/ini.core.php#ini.sect.file-uploads

**Comment by broncowdd** [comment] 2017-01-19 14:15
Yes ! It works perfectly ;-)
T.H.A.N.K.S. \o\ \o/ /o/

**Comment by broncowdd** [comment] 2017-01-19 15:03
Just to share with you: 

## uppie_example (js part)
```
      /* used on a dropzone element */
      var uppie = new Uppie();
      uppie(document.documentElement, function(event, formData, files) {
        var xhr = new XMLHttpRequest();
        // ADDED THIS TO SEND THE PATH INFO AND RECREATE THE FOLDER STRUCTURE ;-)
        Array.prototype.forEach.call(files,function(f){
          formData.append("paths[]",f);
        });
        
        console.log(formData);
        xhr.open('POST', 'get.php');
        xhr.send(formData);

      });
```


## get.php
```
foreach ($_FILES['files']['name'] as $i => $name) {
    if (strlen($_FILES['files']['name'][$i]) > 1) {
    	$fullpath=strip_tags($_POST['paths'][$i]);
    	$path=dirname($fullpath);
        # Here I use the $_POST["path"] data to create all the nedded folders
    	if (!is_dir('uploads/'.$path)){
    		mkdir('uploads/'.$path);
    	}
        if (move_uploaded_file($_FILES['files']['tmp_name'][$i], 'uploads/'.$fullpath)) {
            echo '<li>'.$name.'</li>';
        }
    }
}
```

**Comment by silverwind** [comment] 2017-01-19 16:22
Wonderful idea to send the paths in the same request! I've been doing something similar in the past, but with an out-of-band ajax request. This is much nicer, thanks!

**Comment by silverwind** [comment] 2017-01-19 16:23
If you don't mind, I'd like to add that code as an example in my README.

**Closed as completed by silverwind** 2017-01-19 16:22 UTC

**Comment by broncowdd** [comment] 2017-01-19 18:40
Of course, I'm glad to add something to your work ;-)

**Comment by silverwind** [comment] 2017-01-19 18:48
[Done](https://github.com/silverwind/uppie#php-example), thanks!

**Comment by SumDim** [comment] 2018-04-05 14:27
Hallo,

i tried to get the path from my uploaded file but i only see in my Request-Payload the name of my files. 
I dont know why...

On this page (https://stackoverflow.com/questions/15201071/how-to-get-full-path-of-selected-file-on-change-of-input-type-file-using-jav) they said that this will not work, is that right?

This is my javascript-code:

  var uppie = new Uppie();
  uppie(document.querySelector('.input'), function (event, formData, files) {
  var xhr = new XMLHttpRequest();
  files.forEach(function(path) {
  formData.append("paths[]", path);
  console.log(path);
  });
  xhr.open('POST', 'myPath');
  xhr.send(formData);
});

**Comment by SumDim** [comment] 2018-04-05 16:09
I dont know why but it works with this Code:
Array.prototype.forEach.call(files,function(f){
          formData.append("paths[]",f);
          console.log(f); });

**Comment by silverwind** [comment] 2018-04-05 21:40
You can't get the absolute paths, but you can get relative ones. For example if you upload `dir` with files in it, you get `dir/file` style files. If multiple files are added, you get only the file names.

Not sure what you're doing with `files`. It's a plain Array, so regular `forEach` should work for iteration.
